# Generated by Django 4.0.2 on 2023-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('HR', 'Hard Rock'), ('HM', 'Heavy Metal'), ('DM', 'Death Metal'), ('BM', 'Black Metal'), ('R', 'Rock'), ('LR', 'Lyric Rock'), ('AR', 'Alternative Rock'), ('PR', 'Progressive Rock'), ('T', 'Trance'), ('D', 'Dance')], max_length=5),
        ),
    ]
