# Generated by Django 4.0.2 on 2023-02-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_picture_URL',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
