# Generated by Django 4.1.6 on 2023-02-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
