# Generated by Django 4.1.6 on 2023-02-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='best_song',
            field=models.CharField(default='', max_length=100),
        ),
    ]
