# Generated by Django 4.1.6 on 2023-02-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listing_best_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='best_song',
        ),
    ]
